# **ASSIGNMENT-18: ARTIFICIAL NEURAL NETWORKS**

In [2]:
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score,classification_report
import warnings
warnings.filterwarnings('ignore')

C:\Users\S Tharun Kumar\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

# **Tasks:**

# **1.) Data Exploration and Preprocessing**

In [3]:
df=pd.read_csv('Alphabets_data.csv')
df

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [4]:
df.shape

(20000, 17)

In [5]:
df.size

340000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [7]:
# Missing Values
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [8]:
# Duplicates
df.duplicated().sum()

np.int64(1332)

In [9]:
df.drop_duplicates(inplace=True,ignore_index=True)
df.duplicated().sum()

np.int64(0)

In [10]:
# Statistical Summary
df.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000,18668.000000
mean,4.150793,7.244322,5.279891,5.506910,3.660596,6.919381,7.529409,4.584637,5.201361,8.353171,6.452700,7.924577,3.131455,8.351832,3.796872,7.784390
std,1.879428,3.187660,1.934960,2.178292,2.160555,2.032226,2.319834,2.625714,2.320102,2.468905,2.624673,2.106957,2.323901,1.574853,2.540271,1.657358
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,5.000000,4.000000,4.000000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.000000,7.000000,2.000000,8.000000,2.000000,7.000000
50%,4.000000,8.000000,5.000000,6.000000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.000000,8.000000,3.000000,8.000000,4.000000,8.000000
75%,5.000000,10.000000,6.000000,7.000000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.000000,9.000000,4.000000,9.000000,5.000000,9.000000
max,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000

In [11]:
# Encoding
lab_enc=LabelEncoder()
df['letter']=lab_enc.fit_transform(df['letter'])

In [12]:
df

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,19,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,8,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,3,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,13,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,6,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,19,5,8,7,7,7,7,9,4,8,7,7,8,3,10,8,6
18664,3,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
18665,2,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
18666,19,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
18667,0,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [13]:
# Features
features=df.drop(columns='letter')
features

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,5,8,7,7,7,7,9,4,8,7,7,8,3,10,8,6
18664,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
18665,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
18666,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
18667,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [14]:
# Target
target=df[['letter']]
target

       letter
0          19
1           8
2           3
3          13
4           6
...       ...
18663      19
18664       3
18665       2
18666      19
18667       0

[18668 rows x 1 columns]

# **2.) Model Implementation**

In [15]:
# Train-test-split
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.8,stratify=target,random_state=150)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(14934, 16)
(3734, 16)
(14934, 1)
(3734, 1)

In [16]:
# Scaling
min_max=MinMaxScaler()
x_train=pd.DataFrame(min_max.fit_transform(x_train),columns=x_train.columns)
x_test=pd.DataFrame(min_max.transform(x_test),columns=x_test.columns)

In [17]:
x_train

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,0.333333,0.533333,0.466667,0.400000,0.400000,0.533333,0.466667,0.333333,0.400000,0.600000,0.266667,0.333333,0.200000,0.500000,0.266667,0.600000
1,0.533333,0.733333,0.400000,0.400000,0.200000,0.600000,0.400000,0.200000,0.533333,0.733333,0.266667,0.400000,0.133333,0.642857,0.333333,0.600000
2,0.133333,0.200000,0.200000,0.133333,0.133333,0.600000,0.400000,0.200000,0.333333,0.666667,0.266667,0.400000,0.133333,0.500000,0.133333,0.533333
3,0.333333,0.600000,0.466667,0.533333,0.466667,0.333333,0.533333,0.266667,0.200000,0.533333,0.400000,0.600000,0.333333,0.714286,0.666667,0.600000
4,0.400000,0.466667,0.533333,0.400000,0.600000,0.533333,0.400000,0.333333,0.333333,0.466667,0.400000,0.533333,0.533333,0.642857,0.466667,0.266667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14929,0.133333,0.400000,0.200000,0.266667,0.066667,0.466667,0.333333,0.866667,0.333333,0.466667,0.800000,0.533333,0.200000,0.571429,0.000000,0.533333
14930,0.200000,0.066667,0.333333,0.200000,0.066667,0.466667,0.800000,0.133333,0.200000,0.466667,0.733333,0.600000,0.133333,0.642857,0.066667,0.533333
14931,0.600000,0.933333,0.533333,0.533333,0.400000,0.600000,0.333333,0.266667,0.400000,0.666667,0.266667,0.466667,0.400000,0.500000,0.600000,0.466667
14932,0.266667,0.533333,0.333333,0.400000,0.133333,0.466667,0.400000,0.466667,0.600000,0.400000,0.400000,0.600000,0.133333,0.500000,0.400000,0.733333
14933,0.200000,0.266667,0.266667,0.400000,0.133333,0.466667,0.466667,0.266667,0.933333,0.600000,0.400000,0.533333,0.000000,0.500000,0.533333,0.533333

In [18]:
x_test

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,0.266667,0.666667,0.333333,0.533333,0.200000,0.333333,0.533333,0.533333,0.533333,0.600000,0.533333,0.866667,0.133333,0.571429,0.266667,0.666667
1,0.400000,0.666667,0.533333,0.466667,0.266667,0.333333,0.866667,0.133333,0.400000,0.866667,0.400000,0.133333,0.066667,0.642857,0.133333,0.400000
2,0.200000,0.266667,0.266667,0.200000,0.133333,0.466667,0.466667,0.200000,0.600000,0.400000,0.400000,0.533333,0.200000,0.500000,0.400000,0.533333
3,0.333333,0.666667,0.466667,0.533333,0.400000,0.600000,0.466667,0.466667,0.400000,0.400000,0.400000,0.333333,0.200000,0.571429,0.600000,0.733333
4,0.200000,0.266667,0.266667,0.200000,0.133333,0.200000,0.733333,0.133333,0.133333,0.666667,0.666667,0.533333,0.333333,0.642857,0.066667,0.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3729,0.266667,0.333333,0.466667,0.266667,0.266667,0.333333,0.466667,0.133333,0.533333,0.666667,0.600000,0.666667,0.200000,0.500000,0.266667,0.400000
3730,0.333333,0.666667,0.400000,0.533333,0.200000,0.600000,0.533333,0.400000,0.600000,0.333333,0.400000,0.333333,0.000000,0.500000,0.600000,0.466667
3731,0.333333,0.733333,0.533333,0.533333,0.466667,0.666667,0.533333,0.333333,0.066667,0.400000,0.666667,0.466667,0.600000,0.857143,0.066667,0.333333
3732,0.666667,1.000000,0.600000,0.533333,0.400000,0.600000,0.333333,0.266667,0.466667,0.600000,0.333333,0.466667,0.400000,0.642857,0.400000,0.533333
3733,0.200000,0.133333,0.266667,0.266667,0.200000,0.466667,0.466667,0.333333,0.400000,0.466667,0.400000,0.533333,0.400000,0.500000,0.266667,0.533333

In [19]:
y_train = y_train.values.ravel()
y_test = y_test.values.ravel()

In [20]:
n_classes=26
epochs=20
batch_size=32

In [21]:
ann=tf.keras.models.Sequential()

In [22]:
#To give no of units in hidden layer,we do a calculation ie;no of input neurons*2/3+no. of output neurons
784*(2/3)+10
16*2/3+1

11.666666666666666

In [23]:
# so now we take roundly 12

In [24]:
# Input layer,first hidden layer
ann.add(tf.keras.layers.Dense(units=12,activation='relu'))

In [25]:
12*2/3+1

9.0

In [26]:
# Second hidden layer
ann.add(tf.keras.layers.Dense(units=9,activation='relu'))

In [27]:
# Output layer
ann.add(tf.keras.layers.Dense(units=n_classes,activation='softmax'))

In [28]:
ann.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss=tf.keras.losses.sparse_categorical_crossentropy,metrics=['accuracy']) #Same loss function because ts same dataset for single and multi

In [29]:
x_test.shape

(3734, 16)

In [30]:
history1=ann.fit(x_train,y_train,epochs=epochs,batch_size=batch_size,validation_data=(x_test,y_test)) #Whenever you listen validation give testing data(Its my words)

Epoch 1/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.0883 - loss: 3.1468 - val_accuracy: 0.1805 - val_loss: 2.9141
Epoch 2/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2603 - loss: 2.6121 - val_accuracy: 0.3399 - val_loss: 2.3587
Epoch 3/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.3790 - loss: 2.1978 - val_accuracy: 0.4014 - val_loss: 2.0652
Epoch 4/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4257 - loss: 1.9795 - val_accuracy: 0.4480 - val_loss: 1.8961
Epoch 5/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4601 - loss: 1.8392 - val_accuracy: 0.4826 - val_loss: 1.7760
Epoch 6/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4817 - loss: 1.7436 - val_accuracy: 0.5083 - val_loss: 1.6969
Epoch 7/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4976 - loss: 1.6766 - val_accuracy: 0.5102 - val_loss: 1.6395
Epoch 8/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.5155 - loss: 1.6247 - val_accuracy: 0.5179 - val_loss: 1.5948
Epoch 9/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5250 - loss: 1.5820 - val_accuracy: 0.5289 - val_loss: 1.5539
Epoch 10/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5379 - loss: 1.5449 - val_accuracy: 0.5546 - val_loss: 1.5187
Epoch 11/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.5479 - loss: 1.5117 - val_accuracy: 0.5632 - val_loss: 1.4844
Epoch 12/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5609 - loss: 1.4807 - val_accuracy: 0.5680 - val_loss: 1.4512
Epoch 13/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5678 - loss: 1.4536 - val_accuracy: 0.5782 - val_loss: 1.4263
Epoch 14/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5782 - loss: 1.4274 - val_accuracy: 0.5956 - val_loss: 1.4008
Epoch 15/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5846 - loss: 1.4015 - val_accuracy: 0.5972 - val_loss: 1.3830
Epoch 16/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.5943 - loss: 1.3791 - val_accuracy: 0.6125 - val_loss: 1.3532
Epoch 17/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6014 - loss: 1.3581 - val_accuracy: 0.6154 - val_loss: 1.3299
Epoch 18/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6114 - loss: 1.3390 - val_accuracy: 0.6294 - val_loss: 1.3165
Epoch 19/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6152 - loss: 1.3212 - val_accuracy: 0.6243 - val_loss: 1.2979
Epoch 20/20
467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6207 - loss: 1.3036 - val_accuracy: 0.6310 - val_loss: 1.2812

In [31]:
val_loss,val_acc=ann.evaluate(x_test,y_test) #Finding validation loss and acc so we given testing data if we want find last training accuracy and loss we can give training data simple!
print('val_loss:',val_loss,'val_acc:',val_acc)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6310 - loss: 1.2812
val_loss: 1.281232237815857 val_acc: 0.6309587359428406

# **3.) Hyperparameter Tuning**

In [32]:
# Parameters
hidden_layers_list = [1,2,3]
neurons_list = [32,64]
activations = ['relu','tanh']
learning_rates = [0.001, 0.0005]

In [33]:
results = []
for hidden_layers in hidden_layers_list:
    for neurons in neurons_list:
        for activation in activations:
            for lr in learning_rates:
                model = tf.keras.models.Sequential()
                # input + first hidden layer
                model.add(tf.keras.layers.Dense(neurons, activation=activation, input_shape=(16,)))
               
                # additional hidden layers
                for i in range(hidden_layers - 1):
                    model.add(tf.keras.layers.Dense(neurons, activation=activation))

                # output layer
                model.add(tf.keras.layers.Dense(26, activation='softmax'))

                optimizer = tf.keras.optimizers.Adam(learning_rate=lr)

                model.compile(optimizer=optimizer,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

                history = model.fit(x_train,y_train,epochs=20,batch_size=32,validation_data=(x_test, y_test),verbose=0)

                val_acc = history.history['val_accuracy'][-1]

                results.append((hidden_layers, neurons, activation, lr, val_acc))

                print('No of hidden Layers:',hidden_layers,'Neurons:',neurons,'activation:',activation,'learning rate:',lr,'Accuracy:',val_acc)

No of hidden Layers: 1 Neurons: 32 activation: relu learning rate: 0.001 Accuracy: 0.7233529686927795
No of hidden Layers: 1 Neurons: 32 activation: relu learning rate: 0.0005 Accuracy: 0.677825391292572
No of hidden Layers: 1 Neurons: 32 activation: tanh learning rate: 0.001 Accuracy: 0.7412961721420288
No of hidden Layers: 1 Neurons: 32 activation: tanh learning rate: 0.0005 Accuracy: 0.7032672762870789
No of hidden Layers: 1 Neurons: 64 activation: relu learning rate: 0.001 Accuracy: 0.7619175314903259
No of hidden Layers: 1 Neurons: 64 activation: relu learning rate: 0.0005 Accuracy: 0.7153186798095703
No of hidden Layers: 1 Neurons: 64 activation: tanh learning rate: 0.001 Accuracy: 0.7458489537239075
No of hidden Layers: 1 Neurons: 64 activation: tanh learning rate: 0.0005 Accuracy: 0.735404372215271
No of hidden Layers: 2 Neurons: 32 activation: relu learning rate: 0.001 Accuracy: 0.7793251276016235
No of hidden Layers: 2 Neurons: 32 activation: relu learning rate: 0.0005 Accuracy: 0.6716657876968384
No of hidden Layers: 2 Neurons: 32 activation: tanh learning rate: 0.001 Accuracy: 0.8039636015892029
No of hidden Layers: 2 Neurons: 32 activation: tanh learning rate: 0.0005 Accuracy: 0.7613819241523743
No of hidden Layers: 2 Neurons: 64 activation: relu learning rate: 0.001 Accuracy: 0.803695797920227
No of hidden Layers: 2 Neurons: 64 activation: relu learning rate: 0.0005 Accuracy: 0.7653990387916565
No of hidden Layers: 2 Neurons: 64 activation: tanh learning rate: 0.001 Accuracy: 0.8671665787696838
No of hidden Layers: 2 Neurons: 64 activation: tanh learning rate: 0.0005 Accuracy: 0.8162828087806702
No of hidden Layers: 3 Neurons: 32 activation: relu learning rate: 0.001 Accuracy: 0.8138725161552429
No of hidden Layers: 3 Neurons: 32 activation: relu learning rate: 0.0005 Accuracy: 0.6922870874404907
No of hidden Layers: 3 Neurons: 32 activation: tanh learning rate: 0.001 Accuracy: 0.8452062010765076
No of hidden Layers: 3 Neurons: 32 activation: tanh learning rate: 0.0005 Accuracy: 0.7870916128158569
No of hidden Layers: 3 Neurons: 64 activation: relu learning rate: 0.001 Accuracy: 0.8540439009666443
No of hidden Layers: 3 Neurons: 64 activation: relu learning rate: 0.0005 Accuracy: 0.8061060309410095
No of hidden Layers: 3 Neurons: 64 activation: tanh learning rate: 0.001 Accuracy: 0.9003749489784241
No of hidden Layers: 3 Neurons: 64 activation: tanh learning rate: 0.0005 Accuracy: 0.8709158897399902

In [34]:
best = max(results, key=lambda x: x[4])
print("Best configuration:", best)

Best configuration: (3, 64, 'tanh', 0.001, 0.9003749489784241)

# **4.) Evaluation**

In [35]:
y_pred = ann.predict(x_test)
y_pred = np.argmax(y_pred, axis=1)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [36]:
# Accuracy, Precision, Recall, and F1-score 
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6309587573647563
              precision    recall  f1-score   support

           0       0.83      0.86      0.85       151
           1       0.54      0.64      0.59       146
           2       0.72      0.73      0.72       142
           3       0.56      0.51      0.53       152
           4       0.54      0.52      0.53       145
           5       0.65      0.51      0.57       150
           6       0.82      0.44      0.57       149
           7       0.50      0.43      0.46       141
           8       0.76      0.65      0.70       105
           9       0.74      0.78      0.76       143
          10       0.32      0.21      0.25       144
          11       0.87      0.78      0.82       134
          12       0.73      0.86      0.79       146
          13       0.80      0.70      0.75       138
          14       0.56      0.64      0.60       144
          15       0.70      0.75      0.72       156
          16       0.47      0.62      0.54       152
          17       0.56      0.69      0.62       147
          18       0.28      0.36      0.31       146
          19       0.60      0.54      0.57       150
          20       0.74      0.83      0.78       154
          21       0.75      0.83      0.79       141
          22       0.86      0.85      0.85       145
          23       0.39      0.33      0.36       136
          24       0.65      0.65      0.65       149
          25       0.63      0.66      0.65       128

    accuracy                           0.63      3734
   macro avg       0.64      0.63      0.63      3734
weighted avg       0.64      0.63      0.63      3734

**Discussion of Performance Differences**

- The initial ANN model with **default hyperparameters** achieved an accuracy of **63.09%** on the test dataset.
- The performance was moderate because the model used default settings without optimizing the network architecture or learning parameters.
- After applying **hyperparameter tuning,** the model performance improved significantly.
- The tuned model achieved an accuracy of 90.03%, which is considerably higher than the default model.
- The best configuration included **3 hidden layers, 64 neurons per layer, tanh activation function, and a learning rate of 0.001,** which enhanced the model’s ability to learn complex patterns.
- Overall, **hyperparameter tuning played a crucial role in improving the classification performance of the ANN model.**

# --------------------------------------THE END------------------------------------------